### ISSUE TITLE
it don't install

### ISSUE THREAD

**Issue by lemmon-714** [butaneprotocol/blaze-cardano#152]
npm install ->

```

# npm resolution error report

While resolving: undefined@undefined
Found: typescript@5.5.4
node_modules/typescript
  dev typescript@"^5.5.4" from the root project

Could not resolve dependency:
peer typescript@"4.6.x || 4.7.x || 4.8.x || 4.9.x || 5.0.x || 5.1.x || 5.2.x || 5.3.x || 5.4.x" from typedoc@0.25.13
node_modules/typedoc
  dev typedoc@"^0.25.13" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

"The error message you're seeing indicates that there's a version conflict between the TypeScript version you have installed (5.5.4) and the versions that typedoc@0.25.13 is compatible with. typedoc@0.25.13 only supports TypeScript versions up to 5.4.x, but you've installed 5.5.4.

Here are a few ways you can resolve this issue:

Option 1: Downgrade TypeScript
[..]
Option 2: Update TypeDoc (if possible)
[..]
Option 3: Use --force or --legacy-peer-deps
[..]
Option 4: Use pnpm or yarn
[..]
Choose the option that best fits your project's needs and stability requirements. Let me know if you need further assistance!"

... none of which slap

**Comment by EzePze** [comment]
I've just bumped typedoc, can you try again?

**Comment by lemmon-714** [comment]
thank you! However now I get

npm install
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*

**Comment by ilap** [comment]
> thank you! However now I get
> 
> npm install npm error code EUNSUPPORTEDPROTOCOL npm error Unsupported URL Type "workspace:": workspace:*

Use "pnpm" instead?

**Comment by lemmon-714** [comment]
Oops, didn't catch that. Thanks, it worked <3
